Repository TeamChaRo/ChaRo-Android, pull requests merged in 2022-03, with the labels that each got.

#223 Refactor/221
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/charo_android/data/api/interaction/InteractionService.kt
  app/src/main/java/com/example/charo_android/data/datasource/remote/interaction/RemoteInteractionDataSource.kt
  app/src/main/java/com/example/charo_android/data/datasource/remote/interaction/RemoteInteractionDataSourceImpl.kt
  app/src/main/java/com/example/charo_android/data/datasource/repositoryimpl/interaction/InteractionRepositoryImpl.kt
  app/src/main/java/com/example/charo_android/data/model/interaction/RequestInteractionData.kt
  app/src/main/java/com/example/charo_android/data/model/interaction/ResponseInteractionData.kt
  app/src/main/java/com/example/charo_android/domain/model/detailpost/DetailPost.kt
  app/src/main/java/com/example/charo_android/domain/repository/interaction/InteractionRepository.kt
  app/src/main/java/com/example/charo_android/domain/usecase/CoroutineUseCase.kt
  app/src/main/java/com/example/charo_android/domain/usecase/Result.kt
  app/src/main/java/com/example/charo_android/domain/usecase/interaction/PostLikeUseCase.kt
  app/src/main/java/com/example/charo_android/domain/usecase/interaction/PostSaveUseCase.kt
  app/src/main/java/com/example/charo_android/presentation/di/DataSourceModule.kt
  app/src/main/java/com/example/charo_android/presentation/di/NetworkModule.kt
  app/src/main/java/com/example/charo_android/presentation/di/RepositoryModule.kt
  app/src/main/java/com/example/charo_android/presentation/di/UseCaseModule.kt
  app/src/main/java/com/example/charo_android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostMapFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/viewmodel/DetailPostViewModel.kt
  app/src/main/res/layout/fragment_detail_post.xml
  app/src/main/res/layout/fragment_detail_post_map.xml
  app/src/main/res/values/strings.xml
Labels: feat, refactoring

#226 Feat/225
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/charo_android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/viewmodel/DetailPostViewModel.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/FollowActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/FollowerFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/FollowingFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/adapter/FollowAdapter.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/viewmodel/FollowViewModel.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/adapter/PostAdapter.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/my/MyBottomFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/my/MyTopFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/other/OtherMyPageActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/postlist/SavedPostFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/postlist/WrittenPostFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/viewmodel/OtherMyPageViewModel.kt
  app/src/main/res/drawable/rectangle_border_white_radius_12.xml
  app/src/main/res/layout/activity_other_my_page.xml
  app/src/main/res/layout/fragment_my_bottom.xml
  app/src/main/res/layout/fragment_my_top.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: seunghyeon, style, feat, refactoring

#228 #227 [FIX] : observe 문제 해결
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/my/MyTopFragment.kt
Labels: seunghyeon, fix

#234 Fix/229 code connect
  .idea/gradle.xml
  app/src/main/java/com/example/charo_android/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/home/adapter/HomeCustomThemeAdapter.kt
  app/src/main/java/com/example/charo_android/presentation/ui/home/adapter/HomeLocalDriveAdapter.kt
  app/src/main/java/com/example/charo_android/presentation/ui/home/adapter/HomeTodayDriveAdapter.kt
  app/src/main/java/com/example/charo_android/presentation/ui/home/adapter/HomeTrendDriveAdapter.kt
  app/src/main/java/com/example/charo_android/presentation/ui/onboarding/OnBoardingOneFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/onboarding/OnBoardingThreeFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/onboarding/OnBoardingTwoFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/search/SearchFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/setting/SettingMainFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/signin/SocialSignInActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/signin/viewmodel/SocialSignInViewModel.kt
  app/src/main/java/com/example/charo_android/presentation/ui/signup/SignUpProfileFragment.kt
  app/src/main/java/com/example/charo_android/presentation/util/ResultWrapper.kt
  app/src/main/java/com/example/charo_android/presentation/util/SafeApiCall.kt
  app/src/main/java/com/example/charo_android/presentation/util/SharedInformation.kt
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: hotaek, fix

#237 Feat/233
  app/src/main/java/com/example/charo_android/domain/model/detailpost/DetailPost.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostImageFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/adapter/DetailPostViewPagerAdapter.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/viewmodel/DetailPostViewModel.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/FollowActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/FollowerFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/FollowingFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/adapter/FollowAdapter.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/viewmodel/FollowViewModel.kt
  app/src/main/java/com/example/charo_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/other/OtherMyPageActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/viewmodel/OtherMyPageViewModel.kt
  app/src/main/res/layout/fragment_detail_post.xml
  app/src/main/res/layout/item_my_page_follow.xml
Labels: seunghyeon, style, feat, refactoring, fix

#241 #240 [FEAT] : 비로그인 유저의 API 접근 차단
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/detailpost/DetailPostLikeListFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/FollowerFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/follow/FollowingFragment.kt
  app/src/main/java/com/example/charo_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/example/charo_android/presentation/ui/mypage/other/OtherMyPageActivity.kt
Labels: seunghyeon, feat

#251 #250 [FEAT] : 비로그인 마이페이지 로그인 유도 기능 추가
  app/src/main/java/com/charo/android/presentation/ui/mypage/guest/GuestTopFragment.kt
Labels: seunghyeon, feat
