Repository TeamChaRo/ChaRo-Android, pull requests merged in 2022-04, with the labels that each got.

#256 Fix/255 heart login
  app/src/main/java/com/charo/android/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/home/adapter/HomeCustomThemeAdapter.kt
  app/src/main/java/com/charo/android/presentation/ui/home/adapter/HomeLocalDriveAdapter.kt
  app/src/main/java/com/charo/android/presentation/ui/home/adapter/HomeTodayDriveAdapter.kt
  app/src/main/java/com/charo/android/presentation/ui/home/adapter/HomeTrendDriveAdapter.kt
  app/src/main/java/com/charo/android/presentation/ui/signup/SignUpEmailFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/signup/SignUpPassWordFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/signup/SignUpProfileFragment.kt
  app/src/main/java/com/charo/android/presentation/util/LoginUtil.kt
  app/src/main/res/layout/item_home_today_drive.xml
Labels: hotaek, fix

#258 Feat/242
  .idea/gradle.xml
  app/src/main/java/com/charo/android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/charo/android/presentation/ui/detailpost/DetailPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/detailpost/DetailPostImageFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/detailpost/DetailPostLikeListFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/detailpost/DetailPostMapFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/other/OtherMyPageActivity.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/postlist/SavedPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/postlist/WrittenPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/DialogThemeFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteMapFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteMapLocationFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteMapSearchFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteShareActivity.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteSharedViewModel.kt
  app/src/main/res/layout/fragment_detail_post.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: seunghyeon, feat

#263 #261 [REFACTOR] : 상세보기 서버 API 수정 반영
  app/src/main/java/com/charo/android/data/mapper/DetailPostMapper.kt
  app/src/main/java/com/charo/android/data/model/detailpost/ResponseDetailPost.kt
  app/src/main/java/com/charo/android/domain/model/detailpost/DetailPost.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteSharedViewModel.kt
  app/src/main/res/layout/fragment_detail_post.xml
Labels: seunghyeon, refactoring

#264 Fix/259
  app/src/main/java/com/charo/android/data/api/mypage/MyPageService.kt
  app/src/main/java/com/charo/android/data/datasource/remote/mypage/RemoteMyPageDataSource.kt
  app/src/main/java/com/charo/android/data/datasource/remote/mypage/RemoteMyPageDataSourceImpl.kt
  app/src/main/java/com/charo/android/data/datasource/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  app/src/main/java/com/charo/android/data/model/mypage/ResponseFollow.kt
  app/src/main/java/com/charo/android/domain/repository/mypage/MyPageRepository.kt
  app/src/main/java/com/charo/android/domain/usecase/mypage/GetRemoteFollowUseCase.kt
  app/src/main/java/com/charo/android/presentation/di/UseCaseModule.kt
  app/src/main/java/com/charo/android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/charo/android/presentation/ui/follow/FollowActivity.kt
  app/src/main/java/com/charo/android/presentation/ui/follow/FollowerFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/follow/FollowingFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/other/OtherMyPageActivity.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/viewmodel/OtherMyPageViewModel.kt
  app/src/main/java/com/charo/android/presentation/util/BindingAdapter.kt
  app/src/main/res/layout/activity_other_my_page.xml
  app/src/main/res/layout/item_my_page_post.xml
Labels: seunghyeon, refactoring

#265 Feat/260
  app/src/main/java/com/charo/android/presentation/ui/mypage/postlist/SavedPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/postlist/WrittenPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
Labels: seunghyeon, feat, fix

#267 #266 [FEAT] : 게시물 삭제 API 연결
  app/src/main/java/com/charo/android/data/api/detailpost/DetailPostService.kt
  app/src/main/java/com/charo/android/data/datasource/remote/detailpost/RemoteDetailPostDataSource.kt
  app/src/main/java/com/charo/android/data/datasource/remote/detailpost/RemoteDetailPostDataSourceImpl.kt
  app/src/main/java/com/charo/android/data/datasource/repositoryimpl/detailpost/DetailPostRepositoryImpl.kt
  app/src/main/java/com/charo/android/data/model/detailpost/RequestDeleteDetailPost.kt
  app/src/main/java/com/charo/android/data/model/detailpost/ResponseDeleteDetailPost.kt
  app/src/main/java/com/charo/android/domain/repository/detailpost/DetailPostRepository.kt
  app/src/main/java/com/charo/android/domain/usecase/detailpost/DeleteDetailPostUseCase.kt
  app/src/main/java/com/charo/android/presentation/di/UseCaseModule.kt
  app/src/main/java/com/charo/android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/charo/android/presentation/ui/charo/mypage/MyCharoFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/charo/mypage/SaveFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/charo/otherpage/OtherWriteCharoFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/detailpost/DetailPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/other/OtherMyPageActivity.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/postlist/SavedPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/mypage/postlist/WrittenPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteSharedViewModel.kt
  app/src/main/java/com/charo/android/presentation/util/SingleLiveEvent.kt
  app/src/main/res/layout/dialog_detail_delete.xml
  app/src/main/res/layout/fragment_detail_post.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: seunghyeon, feat

#269 #268 [FEAT] : 스플래시 다음에 올 화면 분기처리
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/charo/android/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/charo/android/presentation/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/charo/android/presentation/util/SharedInformation.kt
  app/src/main/res/layout/activity_splash.xml
Labels: seunghyeon, feat

#270 Feat/268
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/charo/android/data/api/write/WriteViewService.kt
  app/src/main/java/com/charo/android/data/model/write/ResponseEditData.kt
  app/src/main/java/com/charo/android/data/model/write/WriteImgInfo.kt
  app/src/main/java/com/charo/android/presentation/ui/detailpost/DetailPostFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteMapFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteMapLocationFragment.kt
  app/src/main/java/com/charo/android/presentation/ui/write/WriteSharedViewModel.kt
  app/src/main/res/layout/fragment_detail_post.xml
  app/src/main/res/layout/fragment_saved_post.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/values/themes.xml
Labels: seunghyeon, feat, refactoring, fix
